name: Crypto-Analyzer-Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # سيقوم هذا السطر بإعادة تشغيل البوت تلقائياً كل 5 ساعات لضمان استمراريته دون انقطاع
    - cron: '0 */5 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pandas pyTelegramBotAPI requests numpy ccxt flask

      - name: Run Bot Permanently
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          # تشغيل البوت في الخلفية باستخدام علامة &
          python tawsiaaat1111.py &
          
          # إجبار السيرفر على الانتظار وعدم إغلاق الجلسة
          echo "البوت يعمل الآن في الخلفية... السيرفر قيد الانتظار الدائم."
          sleep infinity
