- name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install python-telegram-bot ccxt pandas requests # أضف مكاتب التحليل التي تستخدمها هنا

      - name: Run Crypto Analyzer
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # هذا السطر سيخفي تحذيرات الـ Node.js التي ظهرت لك
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python tawsiaaat1111.py
