steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          # السطر التالي هو الحل لخطأ ModuleNotFoundError
          pip install pandas pyTelegramBotAPI requests numpy ccxt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python tawsiaaat1111.py
